# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, test, and lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: src
        path: /*
  test: 
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14.x]
    steps: 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: src
      - name: Test
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14.x]
    steps: 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: src
      - name: Test
        run: npm run lint
